name: Sync Wiki

on:
  push:
    branches: [master]
  workflow_dispatch:
    
jobs:
  sync:
    name: Sync Wiki
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v2
        
      - name: Sync Wiki
        uses: joeizzard/action-wiki-sync@master
        with:
          username: ${{ github.repository_owner }}
          access_token: ${{ secrets.GITHUB_TOKEN }}
          wiki_folder: docs
          commit_username: github-actions
          commit_email: ${{ secrets.WIKI_GIT_EMAIL }}
          commit_message: 'Action: Updated Wiki'
